from tkinter import *
root = Tk()

b1 = Button(root, text="1", bg="black", fg="grey", padx=50, pady=50)
b2 = Button(root, text="2", bg="black", fg="grey", padx=50, pady=50)
b3 = Button(root, text="3", bg="black", fg="grey", padx=50, pady=50)
b4 = Button(root, text="4", bg="black", fg="grey", padx=50, pady=50)
b5 = Button(root, text="5", bg="black", fg="grey", padx=50, pady=50)
b6 = Button(root, text="6", bg= "black", fg="grey", padx=50, pady=50)
b7 = Button(root, text="7", bg="black", fg="grey", padx=50, pady=50)
b8 = Button(root, text="8", bg="black", fg="grey", padx=50, pady=50)
b9 = Button(root, text="9", bg="black", fg="grey", padx=50, pady=50)
b0 = Button(root, text="0", bg="black", fg="grey", padx=50, pady=50)
b_br = Button(root, text="Thx for using", fg="grey", bg="black")
b_0 = Button(root, text="=", bg="grey", fg="white", padx=50, pady=50)
#breakline
b1.grid(row = 0, column = 0)
b2.grid(row = 0, column = 1)
b3.grid(row = 0, column = 2)
b4.grid(row = 1, column = 0)
b5.grid(row = 1, column = 1)
b6.grid(row = 1, column = 2)
b7.grid(row = 2, column = 0)
b8.grid(row = 2, column = 1)
b9.grid(row = 2, column = 2)
b0.grid(row = 3, column = 1)
b_br.grid(row = 3, column = 0)
b_0.grid(row = 3, column = 2)
root.mainloop()